on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -  name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-2
