on:
  push:
    branches:
      - main
      
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        -  name: Configure AWS credentials
           uses: aws-actions/configure-aws-credentials@v4
           with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: us-east-2

        - name: Debug AWS Configuration
          run: |
            printenv | grep AWS
            ls -la ~/.aws/
            cat ~/.aws/credentials || true
            cat ~/.aws/config || true
